sudo: required

services:
    - docker

env:
    global:
        - IMAGE_SERVICE_TAG: "registry.heroku.com/${HEROKU_USERNAME}-devops_exam/image-service"

before_install:
    - docker login --username "${HEROKU_USERNAME}" --password "${HEROKU_API_KEY}" registry.heroku.com
    - docker build -t "${IMAGE_SERVICE_TAG}" image-service

#script:
#    - <<build test here>>


deploy:
    - provider: script
      script:
          - docker push "${IMAGE_SERVICE_TAG}"
    app: devops-exam-image-service 
    on:
        repo: andrewbermejo20/devops_exam
        branch: development 
