sudo: required

services:
    - docker

env:
    global:
        - HEROKU_APP_NAME: "devops-exam-image-service"
        - IMAGE_SERVICE_HOST: "${HEROKU_APP_NAME}.herokuapp.com"

before_install:
    - npm install -g heroku
    - heroku container:login  

install:
    - sed "s/localhost/${IMAGE_SERVICE_HOST}/g" -i viewer-service/index.html
    - docker-compose build

script:
    - grep -q "${IMAGE_SERVICE_HOST}" viewer-service/index.html
#    - docker-compose up -d image-service
#    - docker ps | grep -q "${HEROKU_APP_NAME}"
#    - docker-compose down

deploy:
    - provider: script
      skip-cleanup: true
      script:
          - heroku container:push --recursive -a "${HEROKU_APP_NAME}"
          - heroku container:release web -a "${HEROKU_APP_NAME}"
      on:
          branch: development 

    - provider: pages
      skip-cleanup: true
      github-token: "${GITHUB_TOKEN}"
      keep-history: true
      local-dir: viewer-service
      on:
          branch: development
