sudo: required

services:
    - docker

env:
    global:
        - HEROKU_APP_NAME: "devops-exam-image-service"
        - IMAGE_SERVICE_HOST: "${HEROKU_APP_NAME}.herokuapp.com"

before_install:
    - npm install -g heroku
    - heroku container:login  

script:
    - heroku container:push --recursive -a "${HEROKU_APP_NAME}"
    - sed "s/localhost/${IMAGE_SERVICE_HOST}/g" -i viewer-service/index.html  


deploy:
    - provider: script
      skip-cleanup: true
      script:
          - heroku container:release web -a "${HEROKU_APP_NAME}"
      on:
          branch: development 

    - provider: pages
      skip-cleanup: true
      github-token: "${GITHUB_TOKEN}"
      keep-history: true
      local-dir: viewer-service
      on:
          branch: development
