sudo: required

services:
    - docker

env:
    global:
        - HEROKU_APP_NAME: "devops-exam-image-service"

before_install:
    - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
    - docker images


deploy:
    - provider: script
      skip-cleanup: true
      script:
              - /usr/local/heroku/bin/heroku container:push web --app "${HEROKU_APP_NAME}"
      on:
          branch: development 

    - provider: pages
      skip-cleanup: true
      github-token: "${GITHUB_TOKEN}"
      keep-history: true
      local-dir: viewer-service
      on:
          branch: development
