version: "3"

services:
    image-service:
        build: 
            context: image-service
            dockerfile: Dockerfile.web
        image: devops-exam-image-service/web
        environment:
                - "PORT: 8888"
        ports:
            - 80:8888

    viewer-service:
        image: nginx:alpine
        volumes:
            - ./viewer-service:/usr/share/nginx/html
        ports:
            - 8080:80

